### ISSUE TITLE
Returning null common_name for all plants

### ISSUE THREAD

**Issue by LorienOlive** [treflehq/trefle-api#22]
**Describe the bug**
Everything was working fine, but all of a sudden all plant objects were returned with all values for "common_name" as null.  I increased the page size to be sure that it wasn't just the first 25, and all 100 had no common_name.  I haven't changed anything in my queries or server, so I am wondering if it's something on Trefle's end.

**To Reproduce**
1. GET "/plants"
2. All results common_name are null

**Expected behavior**
Expect most to have common_name values

**Comment by LorienOlive** [comment]
Addendum: When I run a query on "rosemary" (for example), it does return objects with common_name, but it continues to return null on all object returned from the base "api/plants" call.  I increased the page_size to 1000, and still all null.  I assume that's not intended, but let me know if you think I might be doing something wrong!

**Comment by lambda2** [comment]
Hey @LorienOlive, a lot of plant indeed don't have a common name yet. This is mainly due because the data is still incomplete, and is hard to fill.
For example, if you take the first element of the `/plants` endpoint, `Gazania pectinata`, we don't know how if they really have a commmon name (https://species.wikimedia.org/wiki/Gazania_pectinata).

**Comment by LorienOlive** [comment]
Should all 1000 plants in a single call have null for their common name?
