### ISSUE TITLE
Support for a page size parameter

### ISSUE THREAD

**Issue by SebastianKG** [treflehq/trefle-api#44]
**Is your feature request related to a problem? Please describe.**
Trying to do large-scale processing of the Trefle dataset takes a long time due to the hardcoded page size of 10.

**Describe the solution you'd like**
A page size parameter across all resource-bearing endpoints that changes the amount of results returned. It would be excellent if this went up to at least 1000. The /plants endpoint is a specific painpoint for my use case.

**Describe alternatives you've considered**
The only possible alternative is making tens of thousands of requests instead of hundreds

**Comment by lambda2** [comment]
Hey @SebastianKG, unfortunately we're currently running Trefle in small servers, and can't allow too heavy responses as it will slow down everybody. So in order to ensure a quality service to all users, we prefer to limit to 20 results.
We will soon provide an archive of our database for you to download, and thus avoid iterating on all the plants.

**Comment by SebastianKG** [comment]
@lambda2 having a downloadable archive would actually solve the problem just as well, I will wait for that. Thank you
