### ISSUE TITLE
Add Client side / CORS support

### ISSUE THREAD

**Issue by lambda2** [treflehq/trefle-api#5]

**Comment by paula-yano** [comment]
Do you have an estimated date for this feature ?

**Comment by lambda2** [comment]
Well it's ready, but it really need further testing, so we're testing it

**Comment by ananda-ghosh** [comment]
I can only get a client-side token by using cURL on the command line. When I try to obtain a key programmatically with fetch() in node.js, CORS policy blocks my access to the fetch data because there is no Access-Control-Allow-Origin set in the response header that Trefle.io is returning. So basically, client-side tokens are not returned to browser code even though cURL results show the auth/claim endpoint is responding to requests. 

For reference, these are the only things set in the response header when I use cURL:

HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Sat, 17 Aug 2019 21:55:03 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 372
Connection: keep-alive
cache-control: max-age=0, private, must-revalidate
x-request-id: 2mtt8tp7c4f6ilqi4s133c53
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
**X-Content-Type-Options: nosniff**

As I understand the standard, setting 'nosniff' for X-Content-Type-Options will always enable Cross-Origin Read Blocking on content types of 'application/json' so I think that might have to change along with setting Access-Control-Allow-Origin so that the fetch results can be read in browser code. Not that I really understand much of this, I'm pretty new to interacting with credentialed APIs. But it seems to me there are some more headers that need to set in the response on Trefle.io side for us to be able to actually use these client-side tokens.

Thanks for working on this, it's a great idea.
